name: Build e Release
on:
  push:
    branches:
      - main
    paths:
      - 'src-tauri/tauri.conf.json'

jobs:
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Rust Cache
        uses: swatinem/rust-cache@v2
        with:
          key: ${{ matrix.platform }}

      - name: Install dependencies
        run: npm install

      - name: Install Dependencies (Linux only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev

      - name: Build and Package
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: openapiui-v__VERSION__
          releaseName: "OpenAPIUI v__VERSION__"
          releaseDraft: true
          prerelease: false